<?php

return [
    [
        'brand' => 'Ferrari',
        'model' => '488 GTB',
        'year' => 2015,
        'color' => 'Rosso',
        'price' => 250000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 661,
        'doors' => 2,
        'km' => 10000,
        'used' => false,
    ],
    [
        'brand' => 'Lamborghini',
        'model' => 'Huracan',
        'year' => 2014,
        'color' => 'Nero',
        'price' => 200000.00,
        'engine' => 'V10 Benzina',
        'horsepower' => 610,
        'doors' => 2,
        'km' => 5000,
        'used' => false,
    ],
    [
        'brand' => 'Porsche',
        'model' => '911',
        'year' => 2019,
        'color' => 'Bianco',
        'price' => 150000.00,
        'engine' => 'Boxer 6 Benzina',
        'horsepower' => 443,
        'doors' => 2,
        'km' => 2000,
        'used' => false,
    ],
    [
        'brand' => 'Tesla',
        'model' => 'Model S',
        'year' => 2020,
        'color' => 'Grigio',
        'price' => 90000.00,
        'engine' => 'Elettrico',
        'horsepower' => 778,
        'doors' => 4,
        'km' => 1000,
        'used' => false,
    ],
    [
        'brand' => 'BMW',
        'model' => 'M5',
        'year' => 2018,
        'color' => 'Blu',
        'price' => 120000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 600,
        'doors' => 4,
        'km' => 8000,
        'used' => false,
    ],
    [
        'brand' => 'Audi',
        'model' => 'RS6 Avant',
        'year' => 2017,
        'color' => 'Nero',
        'price' => 110000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 591,
        'doors' => 5,
        'km' => 15000,
        'used' => true,
    ],
    [
        'brand' => 'Mercedes-Benz',
        'model' => 'AMG GT',
        'year' => 2016,
        'color' => 'Argento',
        'price' => 130000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 550,
        'doors' => 2,
        'km' => 12000,
        'used' => true,
    ],
    [
        'brand' => 'Jaguar',
        'model' => 'F-Type',
        'year' => 2019,
        'color' => 'Verde',
        'price' => 100000.00,
        'engine' => 'V6 Benzina',
        'horsepower' => 380,
        'doors' => 2,
        'km' => 6000,
        'used' => false,
    ],
    [
        'brand' => 'Aston Martin',
        'model' => 'Vantage',
        'year' => 2021,
        'color' => 'Grigio',
        'price' => 160000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 503,
        'doors' => 2,
        'km' => 3000,
        'used' => false,
    ],
    [
        'brand' => 'Maserati',
        'model' => 'Quattroporte',
        'year' => 2017,
        'color' => 'Bianco',
        'price' => 90000.00,
        'engine' => 'V6 Diesel',
        'horsepower' => 275,
        'doors' => 4,
        'km' => 20000,
        'used' => true,
    ],
    [
        'brand' => 'Bentley',
        'model' => 'Continental GT',
        'year' => 2020,
        'color' => 'Rosso',
        'price' => 250000.00,
        'engine' => 'W12 Benzina',
        'horsepower' => 626,
        'doors' => 2,
        'km' => 5000,
        'used' => false,
    ],
    [
        'brand' => 'McLaren',
        'model' => '720S',
        'year' => 2021,
        'color' => 'Arancione',
        'price' => 280000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 710,
        'doors' => 2,
        'km' => 2000,
        'used' => false,
    ],
    [
        'brand' => 'Ford',
        'model' => 'Mustang GT',
        'year' => 2019,
        'color' => 'Blu',
        'price' => 50000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 450,
        'doors' => 2,
        'km' => 10000,
        'used' => true,
    ],
    [
        'brand' => 'Chevrolet',
        'model' => 'Camaro SS',
        'year' => 2018,
        'color' => 'Nero',
        'price' => 60000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 455,
        'doors' => 2,
        'km' => 8000,
        'used' => true,
    ],
    [
        'brand' => 'Rolls-Royce',
        'model' => 'Ghost',
        'year' => 2020,
        'color' => 'Bianco',
        'price' => 300000.00,
        'engine' => 'V12 Benzina',
        'horsepower' => 563,
        'doors' => 4,
        'km' => 1000,
        'used' => false,
    ],
    [
        'brand' => 'Bugatti',
        'model' => 'Chiron',
        'year' => 2021,
        'color' => 'Blu',
        'price' => 3000000.00,
        'engine' => 'W16 Benzina',
        'horsepower' => 1500,
        'doors' => 2,
        'km' => 500,
        'used' => false,
    ],
    [
        'brand' => 'Ferrari',
        'model' => 'SF90 Stradale',
        'year' => 2021,
        'color' => 'Rosso',
        'price' => 400000.00,
        'engine' => 'V8 Ibrido',
        'horsepower' => 986,
        'doors' => 2,
        'km' => 1000,
        'used' => false,
    ],
    [
        'brand' => 'Lamborghini',
        'model' => 'Aventador',
        'year' => 2020,
        'color' => 'Giallo',
        'price' => 500000.00,
        'engine' => 'V12 Benzina',
        'horsepower' => 730,
        'doors' => 2,
        'km' => 3000,
        'used' => false,
    ]
];