<?php

return [
    [
        'brand' => 'Ferrari',
        'model' => '488 GTB',
        'year' => 2015,
        'color' => 'Rosso',
        'price' => 250000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 661,
        'doors' => 2,
        'km' => 10000,
        'used' => false,
        'thumb' => 'https://www.ultimatecarpage.com/images/car/5744/Lamborghini-Huracan-LP610-4-36859.jpg',
        'optionals' => ['Navigatore Satellitare', 'Interni in Pelle'],
    ],
    [
        'brand' => 'Lamborghini',
        'model' => 'Huracán LP610-4',
        'year' => 2014,
        'color' => 'Nero',
        'price' => 200000.00,
        'engine' => 'V10 Benzina',
        'horsepower' => 602,
        'doors' => 2,
        'km' => 5000,
        'used' => false,
        'thumb' => 'https://cdn.ferrari.com/cms/network/media/img/resize/5ea6cea901a4636006b49711-16_ferrari-410_superamerica_488_gtb_esterni?width=750&height=550',
        'optionals' => ['Tetto Panoramico', 'Impianto Audio Premium', 'Cerchi in Lega da 20 pollici'],
    ],
    [
        'brand' => 'Porsche',
        'model' => '911 Carrera S',
        'year' => 2019,
        'color' => 'Bianco',
        'price' => 130000.00,
        'engine' => '6 cilindri Boxer Benzina',
        'horsepower' => 443,
        'doors' => 2,
        'km' => 2000,
        'used' => false,
        'thumb' => 'https://cdn.motor1.com/images/mgl/nr6Jx/s3/porsche-911-carrera-992-2019.webp',
        'optionals' => ['Fari Full LED', 'Climatizzatore Bizona', 'Head-Up Display'],
    ],
    [
        'brand' => 'Tesla',
        'model' => 'Model S Performance',
        'year' => 2020,
        'color' => 'Grigio',
        'price' => 90000.00,
        'engine' => 'Elettrico',
        'horsepower' => 762,
        'doors' => 4,
        'km' => 1000,
        'used' => false,
        'thumb' => 'https://carsguide-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,t_default/v1/editorial/2018-bmw-m5-competition-sedan-silver-1001x565-(2).jpg',
        'optionals' => ['Telecamera a 360 gradi', 'Pacchetto Assistenza alla Guida', 'Adaptive Cruise Control'],
    ],
    [
        'brand' => 'BMW',
        'model' => 'M5',
        'year' => 2018,
        'color' => 'Blu',
        'price' => 110000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 600,
        'doors' => 4,
        'km' => 8000,
        'used' => false,
        'thumb' => 'https://media.ed.edmunds-media.com/tesla/model-s/2019/oem/2019_tesla_model-s_sedan_performance_fq_oem_1_1600.jpg',
        'optionals' => ['Sospensioni Attive', 'Sistema di Ricarica Wireless per Smartphone'],
    ],
    [
        'brand' => 'Audi',
        'model' => 'RS6 Avant Performance',
        'year' => 2017,
        'color' => 'Nero',
        'price' => 70000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 605,
        'doors' => 5,
        'km' => 15000,
        'used' => true,
        'thumb' => 'https://car-images.bauersecure.com/wp-images/12403/audi_rs6_perf_01.jpg',
        'optionals' => ['Sensori di Parcheggio', 'Cerchi in Lega da 20 pollici'],
    ],
    [
        'brand' => 'Mercedes-Benz',
        'model' => 'AMG GT S',
        'year' => 2016,
        'color' => 'Argento',
        'price' => 90000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 503,
        'doors' => 2,
        'km' => 12000,
        'used' => true,
        'thumb' => 'https://www.motortrend.com/uploads/sites/5/2015/07/2016-Mercedes-AMG-GT-S-front-three-quarter-in-motion.jpg',
        'optionals' => ['Freni in Carboceramica', 'Sedili Sportivi'],
    ],
    [
        'brand' => 'Jaguar',
        'model' => 'F-Type S',
        'year' => 2019,
        'color' => 'Verde',
        'price' => 80000.00,
        'engine' => 'V6 Benzina',
        'horsepower' => 380,
        'doors' => 2,
        'km' => 6000,
        'used' => false,
        'thumb' => 'https://assets.carandclassic.com/uploads/cars/jaguar/C1696614/2019-jaguar-f-type-r-65e60414c6394.jpg?ar=16%3A9&auto=&fit=crop&h=1200&ixlib=php-4.1.0&q=75&w=1200&s=351ca6f40ae27ac067d6a992d4f6f8ad',
        'optionals' => ['Cerchi in Lega da 20 pollici', 'Impianto Audio Premium'],
    ],
    [
        'brand' => 'Aston Martin',
        'model' => 'Vantage',
        'year' => 2021,
        'color' => 'Grigio',
        'price' => 160000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 503,
        'doors' => 2,
        'km' => 3000,
        'used' => false,
        'thumb' => 'https://images.pistonheads.com/nimg/44321/Vantage_26.jpg',
        'optionals' => ['Head-Up Display', 'Telecamera a 360 gradi'],
    ],
    [
        'brand' => 'Maserati',
        'model' => 'Quattroporte',
        'year' => 2017,
        'color' => 'Bianco',
        'price' => 90000.00,
        'engine' => 'V6 Diesel',
        'horsepower' => 275,
        'doors' => 4,
        'km' => 20000,
        'used' => true,
        'thumb' => 'https://www.clubalfa.it/wp-content/uploads/2017/03/La-nuova-Maserati-Quattroporte-2017-1-1200x900.jpg',
        'optionals' => ['Climatizzatore Bizona', 'Sistema di Intrattenimento Posteriore'],
    ],
    [
        'brand' => 'Bentley',
        'model' => 'Continental GT',
        'year' => 2020,
        'color' => 'Rosso',
        'price' => 250000.00,
        'engine' => 'W12 Benzina',
        'horsepower' => 626,
        'doors' => 2,
        'km' => 5000,
        'used' => false,
        'thumb' => 'https://www.cnet.com/a/img/resize/a4aae98163097b0714f5451173917a0c367abf61/hub/2020/01/20/3a5c8d5b-80a0-4fea-84b2-537bac93d89c/ogi1-2020-bentley-continental-gt-coupe-001.jpg?auto=webp&fit=crop&height=675&width=1200',
        'optionals' => ['Navigatore Satellitare', 'Interni in Pelle'],
    ],
    [
        'brand' => 'McLaren',
        'model' => '720S',
        'year' => 2021,
        'color' => 'Arancione',
        'price' => 280000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 710,
        'doors' => 2,
        'km' => 2000,
        'used' => false,
        'thumb' => 'https://www.m3motorcube.com/wp/wp-content/uploads/2021/03/Medium-13045-McLaren720SGT3X-1024x686.jpg',
        'optionals' => ['Freni in Carboceramica', 'Cerchi in Lega da 20 pollici', 'Sedili Sportivi'],
    ],
    [
        'brand' => 'Ford',
        'model' => 'Mustang GT',
        'year' => 2019,
        'color' => 'Blu',
        'price' => 40000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 460,
        'doors' => 2,
        'km' => 10000,
        'used' => true,
        'thumb' => 'https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/da6e8a1d4896127a9d2adf83461993b45339474c/photos/98mM0op6-zE2Cv35KDJp.ljDej9Zlz.jpeg?t=163760935638',
        'optionals' => ['Sensori di Parcheggio', 'Tetto Panoramico'],
    ],
    [
        'brand' => 'Chevrolet',
        'model' => 'Camaro SS',
        'year' => 2018,
        'color' => 'Nero',
        'price' => 35000.00,
        'engine' => 'V8 Benzina',
        'horsepower' => 455,
        'doors' => 2,
        'km' => 8000,
        'used' => true,
        'thumb' => 'https://www.cnet.com/a/img/resize/cf0febeeb1ad0dad96b51c00bf0ea81d07de654d/hub/2017/11/29/16ceac81-c8e6-42e9-8d2a-7ec18ae5e9a3/2018-chevrolet-camaro-ss-1.jpg?auto=webp&fit=crop&height=675&width=1200',
        'optionals' => ['Cerchi in Lega da 20 pollici', 'Sedili Riscaldati e Ventilati'],
    ],
    [
        'brand' => 'Rolls-Royce',
        'model' => 'Ghost',
        'year' => 2020,
        'color' => 'Bianco',
        'price' => 300000.00,
        'engine' => 'V12 Benzina',
        'horsepower' => 563,
        'doors' => 4,
        'km' => 1000,
        'used' => false,
        'thumb' => 'https://hips.hearstapps.com/hmg-prod/images/2020-rolls-royce-ghost-mmp-1-1585172707.jpg?crop=0.987xw:0.658xh;0,0.250xh&resize=1200:*',
        'optionals' => ['Navigatore Satellitare', 'Head-Up Display', 'Specchietti Retrovisori Antiabbagliamento'],
    ],
    [
        'brand' => 'Bugatti',
        'model' => 'Chiron',
        'year' => 2021,
        'color' => 'Blu',
        'price' => 3000000.00,
        'engine' => 'W16 Benzina',
        'horsepower' => 1500,
        'doors' => 2,
        'km' => 500,
        'used' => false,
        'thumb' => 'https://cdn.motor1.com/images/mgl/QE3q0/s1/2021-bugatti-chiron-super-sport-300.jpg',
        'optionals' => ['Freni in Carboceramica', 'Interni in Pelle', 'Sistema di Ricarica Wireless per Smartphone'],
    ],
    [
        'brand' => 'Ferrari',
        'model' => 'SF90 Stradale',
        'year' => 2021,
        'color' => 'Rosso',
        'price' => 500000.00,
        'engine' => 'V8 Ibrido',
        'horsepower' => 986,
        'doors' => 2,
        'km' => 1000,
        'used' => false,
        'thumb' => 'https://assets.dyler.com/uploads/cars/223067/4874582/medium_962ec94e-a1e2-4706-9d50-52f7c7ce27c0.jpg',
        'optionals' => ['Interni in Pelle', 'Sospensioni Attive', 'Sistema di Ricarica Wireless per Smartphone'],
    ],
    [
        'brand' => 'Lamborghini',
        'model' => 'Aventador SVJ',
        'year' => 2020,
        'color' => 'Giallo',
        'price' => 500000.00,
        'engine' => 'V12 Benzina',
        'horsepower' => 759,
        'doors' => 2,
        'km' => 3000,
        'used' => false,
        'thumb' => 'https://www.bentleylongisland.com/imagetag/2806/main/l/New-2020-Lamborghini-Aventador-SVJ-Roadster-1597949125.jpg',
        'optionals' => ['Freni in Carboceramica', 'Cerchi in Lega da 20 pollici', 'Sedili Sportivi'],
    ],
];